// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGJ8K-mk-sUqLXaNZke1s9IQRR3qvQk-I',
    appId: '1:716518681573:web:f885ca70f3a5bc5e8a1d0c',
    messagingSenderId: '716518681573',
    projectId: 'supply-chain-app-f0e70',
    authDomain: 'supply-chain-app-f0e70.firebaseapp.com',
    storageBucket: 'supply-chain-app-f0e70.firebasestorage.app',
    measurementId: 'G-LNKQT4ZY7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2vXJ1VLdVf1BIv_TzmQVOmsdC2wS8kWk',
    appId: '1:716518681573:android:f67bab611480989f8a1d0c',
    messagingSenderId: '716518681573',
    projectId: 'supply-chain-app-f0e70',
    storageBucket: 'supply-chain-app-f0e70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmLuE5YFS0QDty4esFN81jsigw-lnG8Pk',
    appId: '1:716518681573:ios:775c9d1d7284b0458a1d0c',
    messagingSenderId: '716518681573',
    projectId: 'supply-chain-app-f0e70',
    storageBucket: 'supply-chain-app-f0e70.firebasestorage.app',
    iosBundleId: 'com.example.scrrpaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmLuE5YFS0QDty4esFN81jsigw-lnG8Pk',
    appId: '1:716518681573:ios:775c9d1d7284b0458a1d0c',
    messagingSenderId: '716518681573',
    projectId: 'supply-chain-app-f0e70',
    storageBucket: 'supply-chain-app-f0e70.firebasestorage.app',
    iosBundleId: 'com.example.scrrpaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGJ8K-mk-sUqLXaNZke1s9IQRR3qvQk-I',
    appId: '1:716518681573:web:d3bf2c49d2285ec88a1d0c',
    messagingSenderId: '716518681573',
    projectId: 'supply-chain-app-f0e70',
    authDomain: 'supply-chain-app-f0e70.firebaseapp.com',
    storageBucket: 'supply-chain-app-f0e70.firebasestorage.app',
    measurementId: 'G-T3F1ZD44NZ',
  );
}
