// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNtatDR4g--KMmwtNJcZXg0KntubM8DKI',
    appId: '1:139821605349:web:23e7a043b077db9f420f0c',
    messagingSenderId: '139821605349',
    projectId: 'n-scrrpa',
    authDomain: 'n-scrrpa.firebaseapp.com',
    storageBucket: 'n-scrrpa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQzicWmZi--VAvm35ksUExAujbiemCbx8',
    appId: '1:139821605349:android:adf94c4d6187c738420f0c',
    messagingSenderId: '139821605349',
    projectId: 'n-scrrpa',
    storageBucket: 'n-scrrpa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTeq8WDsG3Tzb7lx1d8I-4kPR3l9pEw3E',
    appId: '1:139821605349:ios:fcbdcb8f500b83da420f0c',
    messagingSenderId: '139821605349',
    projectId: 'n-scrrpa',
    storageBucket: 'n-scrrpa.firebasestorage.app',
    iosBundleId: 'com.example.scrrpaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTeq8WDsG3Tzb7lx1d8I-4kPR3l9pEw3E',
    appId: '1:139821605349:ios:fcbdcb8f500b83da420f0c',
    messagingSenderId: '139821605349',
    projectId: 'n-scrrpa',
    storageBucket: 'n-scrrpa.firebasestorage.app',
    iosBundleId: 'com.example.scrrpaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNtatDR4g--KMmwtNJcZXg0KntubM8DKI',
    appId: '1:139821605349:web:39cb642d63b78685420f0c',
    messagingSenderId: '139821605349',
    projectId: 'n-scrrpa',
    authDomain: 'n-scrrpa.firebaseapp.com',
    storageBucket: 'n-scrrpa.firebasestorage.app',
  );

}